FROM python:3.8-slim

WORKDIR /app
RUN useradd -rms /bin/bash djangoapp && \
mkdir /app/static && \
mkdir /app/media && \
chown -R djangoapp:djangoapp /app && \
chmod 755 /app

COPY --chown=djangoapp:djangoapp . .
RUN pip install --no-cache-dir --upgrade -r requirements.txt

USER djangoapp

ENV PYTHONDONTWRITEBYTECODE=1 \
PYTHONNONBUFFERED=1

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]